import re


def levenshtein_distance(s1, s2):
    """计算两个字符串的编辑距离（Levenshtein 距离）"""
    if len(s1) < len(s2):
        return levenshtein_distance(s2, s1)
    if len(s2) == 0:
        return len(s1)
    prev_row = list(range(len(s2) + 1))
    for i, c1 in enumerate(s1):
        curr_row = [i + 1]
        for j, c2 in enumerate(s2):
            # 插入 / 删除 / 替换
            insertions = prev_row[j + 1] + 1
            deletions = curr_row[j] + 1
            substitutions = prev_row[j] + (c1 != c2)
            curr_row.append(min(insertions, deletions, substitutions))
        prev_row = curr_row
    return prev_row[-1]

# H3C Comware 命令知识库 V2.0
# 每条命令包含：title, explanation, category, knowledge, scenario, related_commands, common_errors, troubleshooting

COMMAND_DB = {
    "system-view": {
        "title": "进入系统视图",
        "explanation": "从用户视图进入系统视图，用于进行全局配置。",
        "category": "基础配置",
        "knowledge": "H3C 设备配置采用视图层级结构，system-view 是进入配置模式的入口命令。",
        "scenario": "初始配置设备、修改全局参数时使用。",
        "related_commands": ["quit", "return", "display version"],
        "common_errors": ["在未进入系统视图时执行全局配置命令，会提示错误"],
        "troubleshooting": "输入 system-view 重新进入系统视图，再执行配置命令。",
    },
    "display current-configuration": {
        "title": "查看当前配置",
        "explanation": "查看设备当前正在使用的完整配置内容。",
        "category": "查看与维护",
        "knowledge": "排查网络问题时，可以先查看当前配置，确认 VLAN、接口、路由等配置是否正确。",
        "scenario": "配置完成后确认内容，或排查故障时核对配置。",
        "related_commands": ["display saved-configuration", "display version", "save"],
        "common_errors": ["输出内容很长，需要配合 more 分页查看"],
        "troubleshooting": "使用 display current-configuration | more 逐页查看，或用 pipe 过滤特定段落。",
    },
    "interface": {
        "title": "进入接口视图",
        "explanation": "进入指定物理接口或逻辑接口的配置模式，例如 interface GigabitEthernet1/0/1。",
        "category": "接口配置",
        "knowledge": "接口视图中的命令通常只影响当前接口，quit 可返回上一级视图。",
        "scenario": "配置单个端口的 VLAN、IP、速率等参数。",
        "related_commands": ["undo interface", "display interface", "port link-type", "ip address"],
        "common_errors": ["接口编号写错导致进入不存在的接口"],
        "troubleshooting": "先用 display interface brief 查看接口列表，确认编号后再进入。",
    },
    "port link-type access": {
        "title": "设置 Access 接口",
        "explanation": "将当前二层接口设置为 Access 类型，用于连接终端设备。",
        "category": "VLAN",
        "knowledge": "Access 接口通常用于连接电脑、打印机等终端，一般只承载一个 VLAN 的流量。",
        "scenario": "交换机端口连接普通电脑或 IP 电话时配置。",
        "related_commands": ["port access vlan", "port link-type trunk", "display port vlan"],
        "common_errors": ["忘记配置 port access vlan，导致接口默认在 VLAN 1"],
        "troubleshooting": "执行 display interface <接口名> 查看当前 VLAN 绑定情况，补配置 port access vlan <VLAN ID>。",
    },
    "port link-type trunk": {
        "title": "设置 Trunk 接口",
        "explanation": "将当前二层接口设置为 Trunk 类型，用于交换机之间互联。",
        "category": "VLAN",
        "knowledge": "Trunk 接口可以同时承载多个 VLAN 的流量，是交换机间互联的常用方式。",
        "scenario": "两台交换机之间、交换机与路由器之间的连接配置。",
        "related_commands": ["port trunk permit vlan", "port link-type access", "display port vlan"],
        "common_errors": ["忘记允许对应 VLAN 通过，导致跨交换机 VLAN 不通"],
        "troubleshooting": "在接口视图下执行 port trunk permit vlan <VLAN ID> 添加允许的 VLAN。",
    },
    "port access vlan": {
        "title": "设置 Access VLAN",
        "explanation": "将当前 Access 接口加入指定 VLAN。",
        "category": "VLAN",
        "knowledge": "例如 port access vlan 10 表示把接口加入 VLAN 10，接入该接口的设备将属于 VLAN 10。",
        "scenario": "为终端设备端口划分 VLAN。",
        "related_commands": ["port link-type access", "vlan", "display port vlan"],
        "common_errors": ["VLAN 未创建就直接引用，会报错"],
        "troubleshooting": "先在系统视图下执行 vlan <ID> 创建 VLAN，再在接口下配置 port access vlan <ID>。",
    },
    "port trunk permit vlan": {
        "title": "允许 Trunk 通过指定 VLAN",
        "explanation": "指定 Trunk 接口允许通过哪些 VLAN 的流量。",
        "category": "VLAN",
        "knowledge": "两台交换机之间使用 Trunk 时，必须手动允许对应 VLAN 通过，默认只允许 VLAN 1。",
        "scenario": "配置交换机互联端口，允许特定 VLAN 跨交换机通信。",
        "related_commands": ["port link-type trunk", "vlan", "display port vlan"],
        "common_errors": ["默认只允许 VLAN 1，其他 VLAN 不通", "VLAN ID 范围错误"],
        "troubleshooting": "执行 port trunk permit vlan <VLAN ID1> <VLAN ID2> ... 添加允许列表；用 display port vlan 验证。",
    },
    "vlan": {
        "title": "创建或进入 VLAN",
        "explanation": "创建指定 VLAN，并进入 VLAN 配置视图。如果 VLAN 已存在，则进入该 VLAN 视图。",
        "category": "VLAN",
        "knowledge": "VLAN 可以把一个物理交换网络划分成多个逻辑广播域，增强安全性和管理灵活性。",
        "scenario": "网络中需要划分多个业务 VLAN 时创建。",
        "related_commands": ["vlan batch", "display vlan", "port access vlan"],
        "common_errors": ["VLAN ID 超出范围（通常 1-4094）", "VLAN 名称含有非法字符"],
        "troubleshooting": "执行 display vlan 查看现有 VLAN，确认 ID 不冲突后再创建。",
    },
    "vlan batch": {
        "title": "批量创建 VLAN",
        "explanation": "一次性创建多个 VLAN，支持连续范围和单个 ID 混合写法。",
        "category": "VLAN",
        "knowledge": "例如 vlan batch 10 20 30-40 表示创建 VLAN 10、20 以及 30 到 40 的所有 VLAN。",
        "scenario": "大规模部署时批量创建多个 VLAN。",
        "related_commands": ["vlan", "display vlan", "undo vlan"],
        "common_errors": ["VLAN ID 重复", "范围写法错误"],
        "troubleshooting": "用 display vlan 确认 VLAN 创建情况，重复的 VLAN 会提示已存在。",
    },
    "ip address": {
        "title": "配置接口 IP 地址",
        "explanation": "为当前三层接口配置 IP 地址和子网掩码。",
        "category": "三层配置",
        "knowledge": "配置 IP 后，可以使用 ping 等工具测试网络连通性。二层接口无法配置 IP。",
        "scenario": "配置三层交换机接口 IP、路由器接口 IP。",
        "related_commands": ["undo ip address", "display ip interface", "ping"],
        "common_errors": ["在二层接口上配置 IP 报错", "IP 地址与子网不匹配"],
        "troubleshooting": "确认接口已切换为三层模式（undo portswitch），再配置 IP；用 display ip interface brief 检查。",
    },
    "undo": {
        "title": "取消配置",
        "explanation": "undo 用于删除或恢复某项已经配置的内容，是 H3C 设备的标准撤销命令。",
        "category": "配置维护",
        "knowledge": "使用 undo 时要确认命令范围，避免误删关键网络配置。",
        "scenario": "删除不需要的配置、恢复默认设置。",
        "related_commands": ["save", "display current-configuration"],
        "common_errors": ["undo 后面跟的命令不完整导致误删", "未确认就执行 undo"],
        "troubleshooting": "执行前先用 display current-configuration 查看影响范围，确认后谨慎操作。",
    },
    "save": {
        "title": "保存配置",
        "explanation": "将当前运行配置保存到设备的启动配置文件中，避免设备重启后配置丢失。",
        "category": "配置维护",
        "knowledge": "完成重要配置后建议及时保存，并在生产环境中做好配置备份。",
        "scenario": "完成所有配置后保存到存储器。",
        "related_commands": ["display saved-configuration", "startup saved-config", "reset config"],
        "common_errors": ["忘记保存导致重启后配置丢失", "存储空间不足保存失败"],
        "troubleshooting": "执行 save 后确认提示信息；如失败检查存储设备空间（display device).",
    },
    "quit": {
        "title": "退出当前视图",
        "explanation": "退出当前配置视图，返回上一级视图。",
        "category": "基础操作",
        "knowledge": "连续使用 quit 可以逐级返回上一级视图，最终回到用户视图。",
        "scenario": "配置完一个视图后返回上级继续其他配置。",
        "related_commands": ["return", "system-view"],
        "common_errors": ["在用户视图下执行 quit 无反应"],
        "troubleshooting": "在用户视图直接输入 return 或按 Ctrl+C 快速返回。",
    },
    "return": {
        "title": "返回用户视图",
        "explanation": "从当前任意配置视图直接返回用户视图。",
        "category": "基础操作",
        "knowledge": "与 quit 相比，return 可以直接返回到用户视图，无需逐级退出。",
        "scenario": "配置过程中需要快速回到用户视图执行 display 命令时。",
        "related_commands": ["quit", "system-view"],
        "common_errors": ["混淆 return 和 quit 的作用"],
        "troubleshooting": "return 直接回用户视图，quit 只退一级，按需使用。",
    },
    "display version": {
        "title": "查看设备版本信息",
        "explanation": "查看设备的软件版本、硬件型号、许可证等信息。",
        "category": "查看与维护",
        "knowledge": "排查兼容性问题时，经常需要查看版本信息确认设备型号和软件版本。",
        "scenario": "设备升级前确认当前版本，或排查兼容性问题时使用。",
        "related_commands": ["display device", "display current-configuration version"],
        "common_errors": ["输出信息很长，不易定位关键内容"],
        "troubleshooting": "用 display version | include Version 过滤关键行。",
    },
    "display device": {
        "title": "查看设备硬件信息",
        "explanation": "查看设备的所有板卡、接口模块等硬件状态信息。",
        "category": "查看与维护",
        "knowledge": "可以用来检查接口模块是否正常插入、电源风扇状态等。",
        "scenario": "设备上架后检查硬件状态，或排查硬件故障时。",
        "related_commands": ["display version", "display interface brief"],
        "common_errors": ["部分信息输出很长"],
        "troubleshooting": "用 display device brief 查看简要信息，或用 pipe 过滤。",
    },
    "display interface": {
        "title": "查看接口详细信息",
        "explanation": "查看指定接口的运行状态、流量统计、错误计数等详细信息。",
        "category": "查看与维护",
        "knowledge": "接口故障排查最重要的命令之一，可以查看丢包、错码、速率协商等信息。",
        "scenario": "接口不通、速率不对、大量错码时的排查。",
        "related_commands": ["display interface brief", "display errors", "ping"],
        "common_errors": ["忘记指定接口名称查看全部信息，输出很长"],
        "troubleshooting": "指定具体接口：display interface GigabitEthernet1/0/1，或先看 brief 再针对性查看详细。",
    },
    "display interface brief": {
        "title": "查看接口简要状态",
        "explanation": "以表格形式快速查看所有接口的 up/down 状态和 IP 地址。",
        "category": "查看与维护",
        "knowledge": "日常巡检最常用的命令之一，可以快速了解整体接口状态。",
        "scenario": "快速检查哪些接口异常、哪些接口没有 IP。",
        "related_commands": ["display interface", "display errors", "ping"],
        "common_errors": ["输出内容很多，需要滚动查看"],
        "troubleshooting": "配合 more 分页：display interface brief | more。",
    },
    "display vlan": {
        "title": "查看 VLAN 信息",
        "explanation": "查看所有 VLAN 的创建情况、成员端口、状态等信息。",
        "category": "VLAN",
        "knowledge": "排查 VLAN 不通问题时，先确认 VLAN 是否创建以及端口是否正确加入。",
        "scenario": "VLAN 配置后确认、VLAN 不通时排查。",
        "related_commands": ["display port vlan", "display interface brief", "vlan"],
        "common_errors": ["VLAN 已创建但端口未加入", "Trunk 端口未允许该 VLAN"],
        "troubleshooting": "检查端口是否加入 VLAN（display port vlan），检查 Trunk 是否允许该 VLAN（display interface）。",
    },
    "display port vlan": {
        "title": "查看端口 VLAN 信息",
        "explanation": "查看每个端口的 VLAN 类型（Access/Trunk/Hybrid）和所属 VLAN。",
        "category": "VLAN",
        "knowledge": "快速定位端口 VLAN 配置是否正确，是 VLAN 排查的核心命令。",
        "scenario": "确认端口是否属于指定 VLAN，检查 Trunk 允许列表。",
        "related_commands": ["display vlan", "display interface brief", "port link-type"],
        "common_errors": ["看不到预期 VLAN 在端口上"],
        "troubleshooting": "检查 Trunk 端口是否用 port trunk permit vlan 允许了该 VLAN，Access 端口是否用 port access vlan 绑定。",
    },
    "display ip interface brief": {
        "title": "查看接口 IP 简要信息",
        "explanation": "查看所有接口的 IP 地址和 up/down 状态。",
        "category": "三层配置",
        "knowledge": "快速确认接口 IP 配置是否正确、接口是否 up。",
        "scenario": "检查 IP 配置、确认接口状态。",
        "related_commands": ["display interface brief", "display ip routing-table", "ping"],
        "common_errors": ["接口显示 IP 正确但不通，可能是路由问题"],
        "troubleshooting": "用 ping 测试连通性，用 display ip routing-table 检查路由表。",
    },
    "display ip routing-table": {
        "title": "查看路由表",
        "explanation": "查看设备当前的 IP 路由表，包括直连、静态和动态路由。",
        "category": "三层配置",
        "knowledge": "路由表是数据包转发的依据，路由缺失是导致不通的常见原因。",
        "scenario": "排查路由不通、配置静态路由后验证。",
        "related_commands": ["ip route-static", "display ip interface brief", "ping"],
        "common_errors": ["路由条目缺失", "路由优先级配置错误"],
        "troubleshooting": "检查目的网段是否有对应路由，确认下一跳可达（ping 测试）。",
    },
    "ip route-static": {
        "title": "配置静态路由",
        "explanation": "手动配置一条静态路由，指定目的网段和下一跳地址或出接口。",
        "category": "三层配置",
        "knowledge": "静态路由适用于小型网络或作为默认路由，配置简单但需要手动维护。",
        "scenario": "小型网络中配置到特定网段的路由，或配置默认路由。",
        "related_commands": ["display ip routing-table", "undo ip route-static", "ping"],
        "common_errors": ["下一跳地址不可达", "目的网段或掩码写错"],
        "troubleshooting": "先 ping 下一跳地址确认可达性，再检查目的网段和掩码是否正确。",
    },
    "dhcp enable": {
        "title": "启用 DHCP 服务",
        "explanation": "在系统视图下启用设备的 DHCP 服务器功能。",
        "category": "DHCP",
        "knowledge": "启用后才能在接口视图下配置 DHCP 池或接口 DHCP 功能。",
        "scenario": "为终端设备自动分配 IP 地址。",
        "related_commands": ["dhcp server ip-pool", "dhcp select interface", "display dhcp pool"],
        "common_errors": ["未启用 DHCP 就直接配置 DHCP 池", "接口 DHCP 和全局 DHCP 冲突"],
        "troubleshooting": "先在系统视图执行 dhcp enable，再配置 DHCP 池或接口 DHCP。",
    },
    "dhcp server ip-pool": {
        "title": "创建 DHCP 地址池",
        "explanation": "创建一个 DHCP 地址池，用于自动分配 IP 地址给客户端。",
        "category": "DHCP",
        "knowledge": "地址池中可以配置网段、网关、DNS 等参数，客户端获取 IP 时自动应用。",
        "scenario": "为特定网段的用户分配 IP 地址。",
        "related_commands": ["dhcp enable", "dhcp select global", "display dhcp pool"],
        "common_errors": ["地址池名称重复", "网段与接口 IP 不在同一子网"],
        "troubleshooting": "用 display dhcp pool 查看地址池状态，确认网段配置正确。",
    },
    "dhcp select interface": {
        "title": "接口模式 DHCP",
        "explanation": "在当前接口下启用接口模式的 DHCP 服务，为该接口所在网段分配 IP。",
        "category": "DHCP",
        "knowledge": "接口模式 DHCP 适合小型网络，配置简单，不需要单独创建地址池。",
        "scenario": "简单网络中为单个网段分配 IP。",
        "related_commands": ["dhcp enable", "dhcp server ip-pool", "display dhcp pool"],
        "common_errors": ["忘记先执行 dhcp enable", "接口是二层接口无法分配 IP"],
        "troubleshooting": "确认已执行 dhcp enable，且接口为三层接口（undo portswitch）。",
    },
    "display dhcp pool": {
        "title": "查看 DHCP 地址池信息",
        "explanation": "查看所有 DHCP 地址池的状态、已分配和剩余地址数量。",
        "category": "DHCP",
        "knowledge": "地址池耗尽是导致终端无法获取 IP 的常见原因。",
        "scenario": "排查终端获取 IP 失败问题。",
        "related_commands": ["dhcp server ip-pool", "display ip interface brief"],
        "common_errors": ["地址池耗尽", "地址租期过长"],
        "troubleshooting": "检查已分配地址数量是否接近总地址数，必要时扩大地址池或缩短租期。",
    },
    "radius-server": {
        "title": "配置 RADIUS 服务器",
        "explanation": "配置设备连接 RADIUS 服务器进行用户认证。",
        "category": "安全配置",
        "knowledge": "RADIUS 是一种常用的集中认证协议，可以实现用户统一管理和计费。",
        "scenario": "企业网络中统一用户认证，SSH/Console 登录认证。",
        "related_commands": ["aaa", "authentication scheme", "display radius scheme"],
        "common_errors": ["RADIUS 服务器地址或密钥配置错误", "服务器不可达"],
        "troubleshooting": "用 ping 测试 RADIUS 服务器可达性，检查共享密钥是否一致。",
    },
    "aaa": {
        "title": "进入 AAA 配置视图",
        "explanation": "进入 AAA（认证、授权、计费）配置视图，进行用户安全管理配置。",
        "category": "安全配置",
        "knowledge": "AAA 可以统一管理用户登录认证方式，支持本地认证和 RADIUS/TACACS+ 认证。",
        "scenario": "配置用户登录认证策略。",
        "related_commands": ["radius-server", "authentication scheme", "authorization scheme"],
        "common_errors": ["配置错误导致自己也被锁定", "认证方式顺序错误"],
        "troubleshooting": "保留本地管理员账号作为备份，先用 console 本地账号登录再调整 AAA 配置。",
    },
    "authentication scheme": {
        "title": "创建认证方案",
        "explanation": "创建 AAA 认证方案，指定认证方式和认证顺序。",
        "category": "安全配置",
        "knowledge": "可以配置多种认证方式（如 RADIUS + 本地），按顺序尝试直到成功。",
        "scenario": "配置多层认证策略，确保认证可靠性。",
        "related_commands": ["aaa", "radius-server", "local-user"],
        "common_errors": ["所有认证方式都配置失败导致无法登录", "方案未应用到用户或模板"],
        "troubleshooting": "确认认证方案已应用到对应的 domain 或用户，检查各认证方式参数。",
    },
    "local-user": {
        "title": "创建本地用户",
        "explanation": "在设备上创建本地用户账号，用于本地认证登录。",
        "category": "安全配置",
        "knowledge": "本地用户是 RADIUS 故障时的最后保障，建议至少保留一个管理员本地账号。",
        "scenario": "创建管理员账号、配置本地认证备份。",
        "related_commands": ["aaa", "authorization scheme", "display local-user"],
        "common_errors": ["密码强度不符合要求", "用户权限级别设置错误"],
        "troubleshooting": "检查密码复杂度要求，确认 service-type 包含所需的登录方式（ssh/console）。",
    },
    "display local-user": {
        "title": "查看本地用户信息",
        "explanation": "查看所有本地用户账号及其配置状态。",
        "category": "安全配置",
        "knowledge": "排查登录问题时，确认用户账号是否存在、权限是否正确。",
        "scenario": "检查本地用户配置、排查登录失败问题。",
        "related_commands": ["local-user", "aaa", "display radius scheme"],
        "common_errors": ["用户被锁定", "service-type 不包含所需登录方式"],
        "troubleshooting": "检查用户状态是否正常，确认 service-type 包含 ssh 或 console。",
    },
    "stelnet": {
        "title": "配置 Stelnet（SSH）",
        "explanation": "配置设备的 SSH 服务，实现加密远程登录。",
        "category": "远程管理",
        "knowledge": "SSH 替代不安全的 Telnet，所有传输数据均加密，是企业标准远程管理方式。",
        "scenario": "替代 Telnet 进行安全远程管理。",
        "related_commands": ["ssh server enable", "aaa", "local-user"],
        "common_errors": ["未生成 RSA 密钥对", "SSH 版本不匹配"],
        "troubleshooting": "执行 rsa local-key-pair generate 生成密钥对，确认客户端使用 SSHv2。",
    },
    "ssh server enable": {
        "title": "启用 SSH 服务器",
        "explanation": "在系统视图下启用设备的 SSH 服务器功能。",
        "category": "远程管理",
        "knowledge": "启用后设备才接受 SSH 连接，需要先配置 AAA 和用户账号。",
        "scenario": "配置 SSH 远程登录前的必要步骤。",
        "related_commands": ["stelnet", "ssh user", "aaa"],
        "common_errors": ["未配置用户就直接启用 SSH", "端口被防火墙拦截"],
        "troubleshooting": "确认已创建 SSH 用户并授权，检查本地防火墙规则。",
    },
    "ssh user": {
        "title": "创建 SSH 用户",
        "explanation": "创建用于 SSH 登录的用户账号，指定认证方式和密码。",
        "category": "远程管理",
        "knowledge": "SSH 用户需要单独创建，与本地 AAA 用户配合使用。",
        "scenario": "配置管理员通过 SSH 远程登录设备。",
        "related_commands": ["ssh server enable", "local-user", "stelnet"],
        "common_errors": ["认证方式配置错误", "密码太简单被拒绝"],
        "troubleshooting": "确认 service-type 包含 ssh，检查密码复杂度是否符合要求。",
    },
    "undo ssh user": {
        "title": "删除 SSH 用户",
        "explanation": "删除指定的 SSH 用户账号。",
        "category": "远程管理",
        "knowledge": "删除用户前先确认没有其他会话使用该账号。",
        "scenario": "用户离职或更换账号时删除旧账号。",
        "related_commands": ["ssh user", "display ssh user"],
        "common_errors": ["删除正在使用的账号导致当前会话断开"],
        "troubleshooting": "先用 display ssh user 查看在线用户，确认安全后再删除。",
    },
    "display ssh user": {
        "title": "查看 SSH 用户信息",
        "explanation": "查看所有 SSH 用户账号及其在线状态。",
        "category": "远程管理",
        "knowledge": "排查 SSH 登录问题时，确认用户是否存在以及是否有活跃会话。",
        "scenario": "检查 SSH 用户配置、查看在线用户。",
        "related_commands": ["ssh user", "stelnet", "display current-configuration"],
        "common_errors": [],
        "troubleshooting": "确认用户状态正常，检查是否有异常登录记录。",
    },
    "telnet": {
        "title": "Telnet 远程登录",
        "explanation": "通过 Telnet 协议远程登录到设备（不推荐，应使用 SSH）。",
        "category": "远程管理",
        "knowledge": "Telnet 传输明文，存在安全风险，新部署应使用 SSH 替代。",
        "scenario": " legacy 设备或临时调试使用。",
        "related_commands": ["stelnet", "ssh server enable"],
        "common_errors": ["Telnet 服务未启用", "被安全策略拒绝"],
        "troubleshooting": "确认 telnet server enable 已配置，检查 ACL 是否放行 Telnet 端口。",
    },
    "telnet server enable": {
        "title": "启用 Telnet 服务器",
        "explanation": "在系统视图下启用设备的 Telnet 服务器功能。",
        "category": "远程管理",
        "knowledge": "Telnet 不安全，建议仅在隔离的管理网络中使用，生产环境使用 SSH。",
        "scenario": "管理网络中临时使用 Telnet。",
        "related_commands": ["telnet", "ssh server enable"],
        "common_errors": ["未启用服务", "端口被占用"],
        "troubleshooting": "确认服务已启用，检查 23 端口是否被其他程序占用。",
    },
    "ntp": {
        "title": "配置 NTP 时间同步",
        "explanation": "配置网络时间协议（NTP），使设备时间与标准时间同步。",
        "category": "系统管理",
        "knowledge": "时间同步对日志分析、故障排查、证书验证等非常重要。",
        "scenario": "设备时间不准确、日志时间混乱时配置。",
        "related_commands": ["display ntp status", "clock set", "ntp enable"],
        "common_errors": ["NTP 服务器不可达", "时区配置错误"],
        "troubleshooting": "用 display ntp status 检查同步状态，确认 NTP 服务器地址和防火墙规则。",
    },
    "display ntp status": {
        "title": "查看 NTP 状态",
        "explanation": "查看设备 NTP 同步状态、参考时钟、偏差等信息。",
        "category": "系统管理",
        "knowledge": "NTP 未同步时日志时间可能错误，影响故障定位。",
        "scenario": "检查时间同步是否正常。",
        "related_commands": ["ntp", "display clock", "clock set"],
        "common_errors": [],
        "troubleshooting": "确认状态显示 synced 或 adjacent，否则检查 NTP 服务器配置和连通性。",
    },
    "display clock": {
        "title": "查看当前时间",
        "explanation": "查看设备的当前日期和时间。",
        "category": "系统管理",
        "knowledge": "排查日志时间问题时首先检查设备时钟是否准确。",
        "scenario": "检查时间是否正确，确认时区设置。",
        "related_commands": ["ntp", "clock set", "display ntp status"],
        "common_errors": ["时区不对导致时间差 8 小时"],
        "troubleshooting": "执行 clock timezone Asia/Shanghai +8 设置时区，再配置 NTP 同步。",
    },
    "clock set": {
        "title": "手动设置时间",
        "explanation": "手动设置设备的日期和时间，通常在 NTP 不可用时临时使用。",
        "category": "系统管理",
        "knowledge": "手动设置的时间不会自动同步，建议配置 NTP 作为长期方案。",
        "scenario": "NTP 服务器暂时不可用时临时修正时间。",
        "related_commands": ["ntp", "display clock"],
        "common_errors": ["时间格式错误", "时区未设置"],
        "troubleshooting": "格式为 clock set HH:MM:SS YYYY-MM-DD，设置后检查 display clock 确认。",
    },
    "logging host": {
        "title": "配置日志服务器",
        "explanation": "指定日志服务器地址，将设备日志发送到远程日志服务器。",
        "category": "系统管理",
        "knowledge": "日志集中管理便于故障分析和审计，是运维最佳实践。",
        "scenario": "部署日志服务器后配置设备上报日志。",
        "related_commands": ["info-center enable", "display logbuffer", "display trapbuffer"],
        "common_errors": ["日志服务器地址错误", "UDP 端口 514 被防火墙拦截"],
        "troubleshooting": "确认日志服务器地址和端口正确，检查防火墙规则，用 display logbuffer 查看本地日志。",
    },
    "info-center enable": {
        "title": "启用信息居中（日志功能）",
        "explanation": "启用设备的日志信息中心功能，所有日志模块才能正常工作。",
        "category": "系统管理",
        "knowledge": "info-center 是 H3C 设备的日志框架，启用后才能查看和转发日志。",
        "scenario": "配置日志功能前的必要步骤。",
        "related_commands": ["logging host", "display logbuffer", "reset logbuffer"],
        "common_errors": ["未启用导致看不到日志"],
        "troubleshooting": "执行 info-center enable 后再次查看日志。",
    },
    "display logbuffer": {
        "title": "查看日志缓冲区",
        "explanation": "查看设备最近产生的日志信息，包括系统日志和告警。",
        "category": "查看与维护",
        "knowledge": "日志是排查故障的第一手资料，记录了接口状态变化、协议邻居关系等重要事件。",
        "scenario": "故障发生后查看近期日志定位原因。",
        "related_commands": ["info-center enable", "logging host", "reset logbuffer"],
        "common_errors": ["日志缓冲区已满，旧日志被覆盖"],
        "troubleshooting": "用 reset logbuffer 清空旧日志重新复现故障，或配置日志服务器持久化保存。",
    },
    "display trapbuffer": {
        "title": "查看告警缓冲区",
        "explanation": "查看设备产生的 SNMP Trap 告警信息。",
        "category": "查看与维护",
        "knowledge": "Trap 是设备主动上报的告警事件，比日志更及时，用于实时监控。",
        "scenario": "查看接口 up/down、认证失败等实时告警。",
        "related_commands": ["display logbuffer", "snmp-agent"],
        "common_errors": [],
        "troubleshooting": "结合 logbuffer 一起分析，trapbuffer 侧重实时告警。",
    },
    "snmp-agent": {
        "title": "配置 SNMP 代理",
        "explanation": "配置 Simple Network Management Protocol 代理，支持网管系统监控设备。",
        "category": "系统管理",
        "knowledge": "SNMP 是网络管理系统监控设备的主要协议，支持 v1/v2c/v3 版本。",
        "scenario": "接入网管系统、配置告警上报。",
        "related_commands": ["display snmp-agent", "snmp-agent community", "snmp-agent target-host"],
        "common_errors": ["社区名（community）配置错误", "版本不匹配"],
        "troubleshooting": "确认 snmp-agent community 和网管系统配置一致，检查 v3 的认证加密参数。",
    },
    "snmp-agent community": {
        "title": "配置 SNMP 社区名",
        "explanation": "配置 SNMP v2c 的社区名称（community string）及访问权限。",
        "category": "系统管理",
        "knowledge": "社区名相当于 SNMP 的密码，read-only 只读，read-write 可读写。",
        "scenario": "配置网管系统能够读取设备信息。",
        "related_commands": ["snmp-agent", "display snmp-agent"],
        "common_errors": ["社区名拼写错误", "访问权限设置过大"],
        "troubleshooting": "确认社区名与网管系统一致，生产环境建议只给 read-only 权限。",
    },
    "undo snmp-agent community": {
        "title": "删除 SNMP 社区名",
        "explanation": "删除指定的 SNMP 社区名配置。",
        "category": "系统管理",
        "knowledge": "删除前确认没有网管系统正在使用该社区名。",
        "scenario": "更换社区名或清理配置。",
        "related_commands": ["snmp-agent community", "display snmp-agent"],
        "common_errors": [],
        "troubleshooting": "执行后在网管系统侧同步更新配置。",
    },
    "arp": {
        "title": "查看 ARP 表",
        "explanation": "查看设备的 ARP 地址解析表，显示 IP 地址与 MAC 地址的对应关系。",
        "category": "查看与维护",
        "knowledge": "ARP 表是二层到三层映射的关键，ARP 欺骗或表项丢失会导致网络中断。",
        "scenario": "排查 IP 冲突、ARP 欺骗、主机无法通信等问题。",
        "related_commands": ["display arp static", "reset arp", "arp whitelist"],
        "common_errors": ["ARP 表项丢失导致同网段不通", "ARP 欺骗攻击"],
        "troubleshooting": "用 reset arp interface 清除异常表项，配置 ARP 白名单防御欺骗攻击。",
    },
    "display arp": {
        "title": "查看 ARP 表详细信息",
        "explanation": "查看完整的 ARP 地址解析表，包括接口、类型、老化时间等信息。",
        "category": "查看与维护",
        "knowledge": "可以按 VLAN 或接口过滤查看，帮助定位特定网段的 ARP 问题。",
        "scenario": "排查 ARP 相关问题时查看详细表项。",
        "related_commands": ["arp", "display interface brief"],
        "common_errors": [],
        "troubleshooting": "用 display arp vlan <ID> 或 display arp interface <if> 过滤查看。",
    },
    "ping": {
        "title": "连通性测试",
        "explanation": "向目标 IP 发送 ICMP 回显请求，测试网络连通性。",
        "category": "查看与维护",
        "knowledge": "最基本的网络诊断工具，可以判断目标是否可达、延迟多大。",
        "scenario": "确认两台设备之间是否连通。",
        "related_commands": ["tracert", "display ip interface brief", "display arp"],
        "common_errors": ["目标设备禁 ping", "中间设备ACL拦截ICMP"],
        "troubleshooting": "ping 不通时先检查本地接口 IP 和路由，再逐跳排查（tracert）。",
    },
    "tracert": {
        "title": "路由追踪",
        "explanation": "追踪数据包从源到目的经过的所有路由节点，诊断路由问题。",
        "category": "查看与维护",
        "knowledge": "可以定位是哪一跳路由出现问题，是排查跨网段不通的重要工具。",
        "scenario": "跨网段通信失败时追踪路由路径。",
        "related_commands": ["ping", "display ip routing-table"],
        "common_errors": ["中间节点禁 ping 导致显示 *"],
        "troubleshooting": "看到 * 时可能是防火墙拦截，用 ping 测试该节点是否可达。",
    },
    "dhcp relay": {
        "title": "配置 DHCP 中继",
        "explanation": "在不同 VLAN 或网段之间转发 DHCP 请求，使单个 DHCP 服务器服务于多个网段。",
        "category": "DHCP",
        "knowledge": "DHCP 广播包不能跨网段，中继功能在三层接口上将 DHCP 请求单播转发到服务器。",
        "scenario": "多 VLAN 环境中使用集中 DHCP 服务器。",
        "related_commands": ["dhcp enable", "dhcp select relay", "display dhcp relay"],
        "common_errors": ["中继地址配置错误", "DHCP 服务器不可达"],
        "troubleshooting": "确认中继指向的 DHCP 服务器地址正确，且三层路由可达。",
    },
    "ospf": {
        "title": "配置 OSPF 路由协议",
        "explanation": "启用 OSPF 动态路由协议，自动学习网段路由并交换路由信息。",
        "category": "动态路由",
        "knowledge": "OSPF 是企业网最常用的内部网关协议（IGP），支持分层设计和快速收敛。",
        "scenario": "中大型网络中自动分发路由，替代静态路由。",
        "related_commands": ["ospf router-id", "area", "network", "display ospf brief"],
        "common_errors": ["Router ID 冲突", "Area 配置错误", "网段宣告不完整"],
        "troubleshooting": "用 display ospf brief 检查邻居状态，确认 Area 0 配置正确，检查接口是否宣告到正确 Area。",
    },
    "ospf router-id": {
        "title": "配置 OSPF Router ID",
        "explanation": "手动指定 OSPF 协议的 Router ID，用于唯一标识 OSPF 路由器的身份。",
        "category": "动态路由",
        "knowledge": "Router ID 选举优先级：手动配置 > 最大 Loopback IP > 最大物理接口 IP。",
        "scenario": "确保 Router ID 稳定，避免选举结果不符合预期。",
        "related_commands": ["ospf", "display ospf brief"],
        "common_errors": ["Router ID 与其他设备重复导致 OSPF 邻居无法建立"],
        "troubleshooting": "用 display ospf brief 检查当前 Router ID，确保全网唯一。",
    },
    "display ospf brief": {
        "title": "查看 OSPF 简要状态",
        "explanation": "查看 OSPF 进程、Area、邻居关系等简要信息。",
        "category": "动态路由",
        "knowledge": "OSPF 邻居关系是路由交换的基础，邻居 Down 会导致路由丢失。",
        "scenario": "检查 OSPF 邻居是否正常建立。",
        "related_commands": ["ospf", "ospf router-id", "display ospf peer"],
        "common_errors": ["邻居状态卡在 Init/2-Way", "Area ID 不匹配"],
        "troubleshooting": "检查两端 Area ID 是否一致，网络类型是否匹配，认证是否一致。",
    },
    "display ospf peer": {
        "title": "查看 OSPF 邻居详情",
        "explanation": "查看 OSPF 邻居的详细状态信息，包括邻居 IP、接口、状态、Area 等。",
        "category": "动态路由",
        "knowledge": "邻居状态为 Full 表示同步完成，其他状态表示仍在建立过程中。",
        "scenario": "OSPF 邻居异常时查看详细状态排查原因。",
        "related_commands": ["display ospf brief", "ospf"],
        "common_errors": ["状态卡在 Exstart/Exchange", "MTU 不匹配"],
        "troubleshooting": "检查接口 MTU 是否一致，确认网络类型（广播/点对点）匹配。",
    },
    "vlanif": {
        "title": "进入 VLAN 接口视图",
        "explanation": "进入指定 VLAN 的三层接口（VLAN Interface）配置视图。",
        "category": "三层配置",
        "knowledge": "VLANIF 接口是三层虚拟接口，配置 IP 后可作为该 VLAN 的网关。",
        "scenario": "为 VLAN 配置网关 IP，实现 VLAN 间路由。",
        "related_commands": ["vlan", "ip address", "display ip interface brief"],
        "common_errors": ["VLAN 不存在时创建 VLANIF 失败", "VLANIF 下的接口未加入该 VLAN"],
        "troubleshooting": "先确认 VLAN 已创建且至少有一个端口加入该 VLAN，再配置 VLANIF。",
    },
    "interface LoopBack": {
        "title": "创建 LoopBack 接口",
        "explanation": "创建一个逻辑回环接口，通常用于 Router ID 或管理地址。",
        "category": "三层配置",
        "knowledge": "LoopBack 接口永远不会 down，是配置稳定 Router ID 的最佳选择。",
        "scenario": "OSPF/BGP 配置时指定稳定的 Router ID，或作为设备管理地址。",
        "related_commands": ["ip address", "display interface LoopBack", "ospf"],
        "common_errors": ["IP 地址与现有网段冲突"],
        "troubleshooting": "选择一个不在任何物理网段中的 IP，如 10.255.255.1/32。",
    },
    "acl": {
        "title": "创建 ACL 规则",
        "explanation": "创建访问控制列表（ACL），用于过滤流量或匹配策略。",
        "category": "安全配置",
        "knowledge": "H3C 支持基于编号（2000-2999 基本，3000-3999 高级）和基于名称的 ACL。",
        "scenario": "控制特定流量通过、保护设备管理接口。",
        "related_commands": ["acl rule", "traffic-filter", "display acl"],
        "common_errors": ["ACL 规则顺序错误", "忘记应用到接口"],
        "troubleshooting": "用 display acl 查看规则命中计数，确认 ACL 已应用到正确接口的入/出方向。",
    },
    "acl rule": {
        "title": "配置 ACL 规则条目",
        "explanation": "在 ACL 中添加入站或出站规则，指定允许或拒绝的流量条件。",
        "category": "安全配置",
        "knowledge": "ACL 规则按序号从小到大匹配，匹配后即停止，规则顺序非常重要。",
        "scenario": "精细控制哪些 IP 或端口可以访问设备。",
        "related_commands": ["acl", "traffic-filter", "undo acl rule"],
        "common_errors": ["规则序号冲突", "逻辑取反（permit/deny 写反）"],
        "troubleshooting": "检查规则序号是否连续，确认 permit/deny 逻辑正确，用 display acl 验证命中计数。",
    },
    "traffic-filter": {
        "title": "应用 ACL 流量过滤",
        "explanation": "将 ACL 应用到接口的入方向或出方向，实现对流量的控制。",
        "category": "安全配置",
        "knowledge": "traffic-filter 只能在接口视图下配置，inbound 表示入方向，outbound 表示出方向。",
        "scenario": "在接口上实施访问控制策略。",
        "related_commands": ["acl", "acl rule", "display traffic-filter"],
        "common_errors": ["ACL 未创建就应用", "方向搞错"],
        "troubleshooting": "确认 ACL 已创建并包含规则，检查 inbound/outbound 方向是否正确。",
    },
    "mac-address": {
        "title": "配置静态 MAC 地址表",
        "explanation": "手动绑定 MAC 地址到指定接口，防止 MAC 地址漂移或欺骗。",
        "category": "安全配置",
        "knowledge": "静态 MAC 表项不会老化，适合绑定重要设备（如服务器、打印机）。",
        "scenario": "防止 MAC 地址欺骗攻击，或固定重要设备的端口绑定。",
        "related_commands": ["display mac-address", "undo mac-address"],
        "common_errors": ["MAC 地址格式错误", "接口不存在"],
        "troubleshooting": "用 display mac-address 确认当前动态表项，再添加静态绑定。",
    },
    "port-security": {
        "title": "配置端口安全",
        "explanation": "在接口上启用端口安全功能，限制允许学习的 MAC 地址数量。",
        "category": "安全配置",
        "knowledge": "端口安全可以防止非法设备接入网络，超过最大 MAC 数后可以选择 shutdown 或 protect 模式。",
        "scenario": "接入层端口防止私接 Hub 或非法设备。",
        "related_commands": ["mac-address", "display port-security", "undo port-security"],
        "common_errors": ["最大 MAC 数设置过小", "违规动作选择 shutdown 导致端口关闭"],
        "troubleshooting": "根据实际接入设备数量调整 max-mac-num，违规动作建议选 protect 而非 shutdown。",
    },
    "storm-control": {
        "title": "配置广播风暴控制",
        "explanation": "限制接口上广播、组播或未知单播流量的速率，防止风暴影响网络。",
        "category": "安全配置",
        "knowledge": "当接口收到过量广播包时自动限速，保护整段网络不因单个端口异常而瘫痪。",
        "scenario": "接入层防止终端产生广播风暴。",
        "related_commands": ["display storm-control", "undo storm-control"],
        "common_errors": ["阈值设置过低导致正常流量被抑制"],
        "troubleshooting": "根据端口速率合理设置阈值，一般设为端口带宽的 5% 左右。",
    },
    "dhcp snooping": {
        "title": "配置 DHCP Snooping",
        "explanation": "启用 DHCP Snooping 功能，防止私设 DHCP 服务器攻击。",
        "category": "安全配置",
        "knowledge": "Snooping 会监听 DHCP 交互过程，只信任上联端口的 DHCP 响应，非法 DHCP 服务器发出的 Offer 被丢弃。",
        "scenario": "防止内部私接 DHCP 服务器导致用户获取错误 IP。",
        "related_commands": ["dhcp snooping enable", "display dhcp snooping"],
        "common_errors": ["信任端口配置错误导致合法 DHCP 响应被丢弃"],
        "troubleshooting": "确认上联端口已配置为 trusted，其他端口默认不信任。",
    },
    "arp whitelist": {
        "title": "配置 ARP 白名单",
        "explanation": "将指定的 IP-MAC 绑定加入白名单，防御 ARP 欺骗攻击。",
        "category": "安全配置",
        "knowledge": "白名单机制只允许表项中的 IP-MAC 对通信，其他 ARP 报文被丢弃。",
        "scenario": "关键服务器防止 ARP 欺骗导致通信中断。",
        "related_commands": ["arp", "display arp whitelist"],
        "common_errors": ["白名单条目过多影响性能", "IP 或 MAC 写错"],
        "troubleshooting": "仅对关键设备配置白名单，用 display arp whitelist 检查条目。",
    },
    "ssh inbound user password": {
        "title": "配置 SSH 登录密码",
        "explanation": "为 SSH 登录用户设置密码认证方式。",
        "category": "安全配置",
        "knowledge": "SSH 支持密码和公钥两种认证方式，密码方式更通用。",
        "scenario": "配置管理员通过密码登录 SSH。",
        "related_commands": ["ssh user", "stelnet", "aaa"],
        "common_errors": ["密码复杂度不符合要求"],
        "troubleshooting": "密码需包含大小写字母、数字和特殊字符中的至少三种。",
    },
    "radius scheme": {
        "title": "创建 RADIUS 方案",
        "explanation": "创建 AAA RADIUS 认证方案，配置 RADIUS 服务器组及超时重传参数。",
        "category": "安全配置",
        "knowledge": "RADIUS 方案可以配置主备多个服务器，实现认证冗余。",
        "scenario": "企业级统一认证部署。",
        "related_commands": ["radius-server", "aaa", "authentication scheme"],
        "common_errors": ["服务器组名称与认证方案不一致", "超时时间过短导致误判"],
        "troubleshooting": "确认 scheme 名称与 radius-server 配置一致，超时时间建议 5 秒以上。",
    },
    "authorization scheme": {
        "title": "创建授权方案",
        "explanation": "创建 AAA 授权方案，定义用户认证通过后的权限级别和服务类型。",
        "category": "安全配置",
        "knowledge": "授权决定用户登录后能执行哪些命令，是 AAA 安全策略的重要组成部分。",
        "scenario": "区分不同管理员的权限等级。",
        "related_commands": ["aaa", "authentication scheme", "local-user"],
        "common_errors": ["授权级别设置过高或过低"],
        "troubleshooting": "根据实际需求设置 authorization-level，普通管理员建议级别 1-3。",
    },
    "display configuration": {
        "title": "查看设备配置（旧命令）",
        "explanation": "H3C 旧版本中查看当前配置命令，新版本已统一使用 display current-configuration。",
        "category": "查看与维护",
        "knowledge": "不同 Comware 版本命令略有差异，新版推荐用 display current-configuration。",
        "scenario": "在旧版本设备上查看配置。",
        "related_commands": ["display current-configuration", "display saved-configuration"],
        "common_errors": ["新版本不支持该命令"],
        "troubleshooting": "改用 display current-configuration 查看。",
    },
    "display saved-configuration": {
        "title": "查看已保存的配置",
        "explanation": "查看设备启动配置文件中保存的配置内容，即重启后生效的配置。",
        "category": "查看与维护",
        "knowledge": "running-config（当前配置）和 saved-config（保存配置）可能不同，save 后两者才会一致。",
        "scenario": "确认配置是否已保存，或对比当前配置与保存配置差异。",
        "related_commands": ["display current-configuration", "save"],
        "common_errors": ["忘记 save 导致重启后配置丢失"],
        "troubleshooting": "对比两个显示结果，如果不一致说明有未保存的改动，执行 save。",
    },
    "startup saved-config": {
        "title": "指定启动配置文件",
        "explanation": "指定设备启动时使用的配置文件，可用于备份恢复或切换配置版本。",
        "category": "配置维护",
        "knowledge": "一个设备可以保存多个配置文件，启动时选择其中一个作为运行配置。",
        "scenario": "配置备份恢复、切换不同配置版本。",
        "related_commands": ["save", "display startup"],
        "common_errors": ["配置文件不存在", "文件名写错"],
        "troubleshooting": "用 display startup 查看当前启动配置文件名，确认文件存在。",
    },
    "display startup": {
        "title": "查看启动配置信息",
        "explanation": "查看设备启动时使用的配置文件以及系统软件版本信息。",
        "category": "查看与维护",
        "knowledge": "启动配置文件损坏会导致设备无法启动，需通过 TFTP 恢复。",
        "scenario": "检查设备启动配置是否正常。",
        "related_commands": ["startup saved-config", "display current-configuration"],
        "common_errors": [],
        "troubleshooting": "确认 main.cfg 或同等主配置文件存在且不为空。",
    },
    "reload": {
        "title": "重启设备",
        "explanation": "重启设备，通常在配置完成后或故障恢复时使用。",
        "category": "配置维护",
        "knowledge": "重启会中断所有业务，务必确认已保存配置并在业务低峰期操作。",
        "scenario": "配置更新后重启生效，或系统异常时重启恢复。",
        "related_commands": ["save", "display startup"],
        "common_errors": ["未保存配置就重启导致配置丢失"],
        "troubleshooting": "重启前务必执行 save 保存配置，并确认 display startup 显示的配置文件存在。",
    },
    "reset config": {
        "title": "恢复出厂配置",
        "explanation": "清除设备所有配置，恢复为出厂默认状态。",
        "category": "配置维护",
        "knowledge": "此操作不可逆，会删除所有配置，包括 IP、VLAN、路由等，务必谨慎使用。",
        "scenario": "设备交接、故障排查时排除配置干扰。",
        "related_commands": ["save", "reload"],
        "common_errors": ["误操作导致生产配置被清除"],
        "troubleshooting": "执行前务必备份配置（display current-configuration > backup.cfg），确认后再执行。",
    },
    "display bandwidth": {
        "title": "查看接口带宽信息",
        "explanation": "查看指定接口的带宽配置和实际使用速率。",
        "category": "查看与维护",
        "knowledge": "接口速率不匹配（一端 100M 一端 1000M）会导致性能下降或链路抖动。",
        "scenario": "排查接口速率异常、带宽不足问题。",
        "related_commands": ["display interface", "speed", "duplex"],
        "common_errors": [],
        "troubleshooting": "对比两端接口速率设置，确保一致；用 display interface 查看实际协商速率。",
    },
    "speed": {
        "title": "配置接口速率",
        "explanation": "手动设置接口速率（10/100/1000 Mbps）。",
        "category": "接口配置",
        "knowledge": "一般推荐让接口自动协商（auto），手动指定仅在特殊场景下使用。",
        "scenario": "接口速率协商异常时强制指定。",
        "related_commands": ["duplex", "interface", "display interface"],
        "common_errors": ["速率与对端不匹配导致链路 flapping"],
        "troubleshooting": "确保两端速率一致，建议先改一端再改另一端。",
    },
    "duplex": {
        "title": "配置接口双工模式",
        "explanation": "手动设置接口双工模式（全双工 full / 半双工 half）。",
        "category": "接口配置",
        "knowledge": "双工不匹配会产生大量错码和性能下降，是常见故障原因之一。",
        "scenario": "接口速率协商异常时强制指定双工模式。",
        "related_commands": ["speed", "interface", "display interface"],
        "common_errors": ["双工与对端不匹配"],
        "troubleshooting": "两端必须一致（full/full），用 display interface 确认协商结果。",
    },
    "undo speed": {
        "title": "恢复接口速率自动协商",
        "explanation": "取消手动速率设置，恢复接口自动协商速率。",
        "category": "接口配置",
        "knowledge": "大多数场景下应该使用自动协商，手动设置仅在特殊需求时使用。",
        "scenario": "接口速率异常时恢复自动协商。",
        "related_commands": ["speed", "undo duplex", "display interface"],
        "common_errors": [],
        "troubleshooting": "执行后等待接口重新协商，用 display interface 确认速率恢复正常。",
    },
    "undo duplex": {
        "title": "恢复接口双工自动协商",
        "explanation": "取消手动双工设置，恢复接口自动协商双工模式。",
        "category": "接口配置",
        "knowledge": "与 undo speed 配合使用，完全恢复自动协商。",
        "scenario": "接口双工异常时恢复。",
        "related_commands": ["duplex", "undo speed", "display interface"],
        "common_errors": [],
        "troubleshooting": "执行后检查接口状态是否正常 up。",
    },
    "interface range": {
        "title": "批量进入接口视图",
        "explanation": "批量进入多个接口视图，一次性对多个接口执行相同配置。",
        "category": "接口配置",
        "knowledge": "接口范围语法因设备型号而异，常见写法：interface range GigabitEthernet 1/0/1 to 1/0/24。",
        "scenario": "批量配置多个端口的 VLAN、速率等参数。",
        "related_commands": ["interface", "port link-type", "port access vlan"],
        "common_errors": ["范围写法设备不兼容", "批量误操作影响多个端口"],
        "troubleshooting": "先在一个接口测试配置正确，再批量应用；用 display interface range 确认范围。",
    },
    "monitor-port": {
        "title": "配置端口镜像监控端口",
        "explanation": "将指定接口设置为端口镜像的监控端口，用于连接抓包设备。",
        "category": "查看与维护",
        "knowledge": "端口镜像可以将指定端口的流量复制到监控端口，用于网络分析和故障排查。",
        "scenario": "网络抓包分析、流量监控。",
        "related_commands": ["mirror-port", "display mirroring"],
        "common_errors": ["监控端口速率过低丢失数据包"],
        "troubleshooting": "监控端口速率应不低于被镜像端口，建议用千兆或更高速率端口。",
    },
    "mirror-port": {
        "title": "配置端口镜像被镜像端口",
        "explanation": "指定需要被镜像的源端口及监控方向（ inbound/outbound/both）。",
        "category": "查看与维护",
        "knowledge": "可以镜像入方向、出方向或双向流量，根据分析需求选择。",
        "scenario": "抓取特定端口的流量进行分析。",
        "related_commands": ["monitor-port", "display mirroring"],
        "common_errors": ["镜像方向搞错", "源端口不存在"],
        "troubleshooting": "确认源端口存在且方向正确，用 display mirroring 查看镜像配置状态。",
    },
    "display mirroring": {
        "title": "查看端口镜像配置",
        "explanation": "查看当前端口镜像的配置状态和会话信息。",
        "category": "查看与维护",
        "knowledge": "确认镜像配置是否正确生效，监控端口是否正常接收镜像流量。",
        "scenario": "端口镜像配置后验证、故障排查。",
        "related_commands": ["monitor-port", "mirror-port"],
        "common_errors": [],
        "troubleshooting": "在监控端口连接抓包工具，确认有流量进入。",
    },
    "display mac-address": {
        "title": "查看 MAC 地址表",
        "explanation": "查看交换机当前的 MAC 地址学习表，显示 MAC 地址与端口的对应关系。",
        "category": "查看与维护",
        "knowledge": "MAC 地址表是交换机转发数据帧的依据，表项异常可能导致通信故障。",
        "scenario": "排查终端无法通信、MAC 地址漂移问题。",
        "related_commands": ["mac-address", "display interface brief"],
        "common_errors": ["MAC 表项异常增多可能是环路", "MAC 地址频繁漂移"],
        "troubleshooting": "用 display mac-address interface <if> 查看特定端口，检查是否有 MAC 漂移。",
    },
    "display stp brief": {
        "title": "查看 STP 简要状态",
        "explanation": "查看生成树协议（STP）的简要状态，包括各端口的角色和状态。",
        "category": "查看与维护",
        "knowledge": "STP 用于消除二层环路，端口状态异常（如一直处于 Listening/Learning）会导致部分端口不通。",
        "scenario": "排查二层环路、端口不通问题。",
        "related_commands": ["stp", "display stp", "spanning-tree"],
        "common_errors": ["根桥选举不符合预期", "端口角色错误"],
        "troubleshooting": "用 display stp brief 检查各端口角色，确认根桥和根端口符合设计。",
    },
    "stp": {
        "title": "进入 STP 配置视图",
        "explanation": "进入生成树协议配置视图，修改 STP 参数。",
        "category": "二层控制",
        "knowledge": "STP 可以防止二层环路导致的广播风暴，但会增加收敛时间。",
        "scenario": "调整 STP 根桥优先级、端口优先级等参数。",
        "related_commands": ["stp root", "stp priority", "display stp brief"],
        "common_errors": ["根桥优先级设置错误导致拓扑不符合预期"],
        "troubleshooting": "确认核心交换机的根桥优先级最低（数值最小），用 display stp 验证。",
    },
    "stp root": {
        "title": "设置根桥",
        "explanation": "将当前设备设置为 STP 根桥或备份根桥。",
        "category": "二层控制",
        "knowledge": "根桥是 STP 拓扑的基准点，通常将核心交换机设为根桥以保证最优路径。",
        "scenario": "规划 STP 根桥位置，优化网络拓扑。",
        "related_commands": ["stp", "stp priority", "display stp brief"],
        "common_errors": ["多台设备都设为根桥导致冲突"],
        "troubleshooting": "只在一台核心设备上配置 stp root primary，其他设备用 stp root secondary。",
    },
    "stp priority": {
        "title": "配置 STP 优先级",
        "explanation": "手动设置设备的 STP 优先级（0-61440，步长 4096），数值越小优先级越高。",
        "category": "二层控制",
        "knowledge": "默认优先级为 32768，根桥应选择最低数值（如 0 或 4096）。",
        "scenario": "精细控制根桥选举结果。",
        "related_commands": ["stp", "stp root", "display stp brief"],
        "common_errors": ["优先级相同导致随机选举", "数值不是 4096 的倍数"],
        "troubleshooting": "优先级必须是 4096 的倍数，确保 desired 根桥数值最小。",
    },
    "spanning-tree": {
        "title": "启用 spanning-tree",
        "explanation": "在接口或全局启用 Spanning Tree Protocol，防止二层环路。",
        "category": "二层控制",
        "knowledge": "H3C 设备默认启用 STP，多数场景不需要手动操作。",
        "scenario": "在特定接口上手动启用或禁用 STP。",
        "related_commands": ["stp", "display stp brief"],
        "common_errors": ["接口 STP 被误禁用导致环路"],
        "troubleshooting": "确认不需要 STP 的接口（如连接服务器的直连端口）可以关闭 STP 加速收敛。",
    },
    "vlan filter": {
        "title": "VLAN 流量过滤",
        "explanation": "在接口上过滤指定 VLAN 的流量，控制哪些 VLAN 可以通过。",
        "category": "VLAN",
        "knowledge": "除了 Trunk 端口的 permit vlan 外，还可以用 vlan filter 实现更细粒度的 VLAN 过滤。",
        "scenario": "限制某些 VLAN 流量通过特定接口。",
        "related_commands": ["port trunk permit vlan", "vlan"],
        "common_errors": ["过滤方向搞错"],
        "troubleshooting": "确认 inbound/outbound 方向，用 display interface 验证。",
    },
    "display vlan brief": {
        "title": "查看 VLAN 简要信息",
        "explanation": "以简要表格形式查看所有 VLAN 的状态和成员端口数量。",
        "category": "查看与维护",
        "knowledge": "比 display vlan 更简洁，适合快速巡检 VLAN 创建情况。",
        "scenario": "快速检查所有 VLAN 是否创建正常。",
        "related_commands": ["display vlan", "display port vlan"],
        "common_errors": [],
        "troubleshooting": "确认所有预期 VLAN 存在且状态为 Active。",
    },
    "display vlan <id>": {
        "title": "查看指定 VLAN 详情",
        "explanation": "查看指定 VLAN 的详细信息，包括成员端口、接口类型等。",
        "category": "查看与维护",
        "knowledge": "排查特定 VLAN 不通问题时，查看其成员端口是否正确。",
        "scenario": "检查特定 VLAN 的配置和成员情况。",
        "related_commands": ["display vlan", "display port vlan"],
        "common_errors": [],
        "troubleshooting": "确认 VLAN 状态为 Active 且有端口加入。",
    },
    "interface Vlanif": {
        "title": "进入 Vlanif 接口视图（同 vlanif）",
        "explanation": "进入指定 VLAN 的三层接口配置视图，用于配置 VLAN 网关 IP。",
        "category": "三层配置",
        "knowledge": "Vlanif 和 vlanif 是同一概念的不同写法，H3C 两种写法均支持。",
        "scenario": "配置 VLAN 网关 IP 地址。",
        "related_commands": ["vlanif", "ip address", "display ip interface brief"],
        "common_errors": ["VLAN 不存在时报错"],
        "troubleshooting": "先确认 VLAN 已创建，再配置 Vlanif 接口 IP。",
    },
    "interface Eth-Trunk": {
        "title": "创建 Eth-Trunk 聚合组",
        "explanation": "创建以太网链路聚合组，将多个物理端口绑定为一个逻辑端口，提升带宽和可靠性。",
        "category": "接口配置",
        "knowledge": "链路聚合可以负载均衡、提高带宽，并在一根光纤断开时自动切换，是数据中心常用技术。",
        "scenario": "交换机之间需要大带宽互联、提高链路可靠性。",
        "related_commands": ["interface range", "mode manual load-balance", "display eth-trunk"],
        "common_errors": ["聚合组两端模式不一致", "成员端口配置冲突"],
        "troubleshooting": "确认两端都配置了 Eth-Trunk 且模式一致（manual load-balance 或 LACP），成员端口不要单独配置其他参数。",
    },
    "mode manual load-balance": {
        "title": "配置 Eth-Trunk 手动负载分担模式",
        "explanation": "将 Eth-Trunk 接口设置为手动负载分担模式，不依赖 LACP 协议。",
        "category": "接口配置",
        "knowledge": "手动模式配置简单，适合两端设备不支持 LACP 的场景；LACP 模式可以自动管理成员端口。",
        "scenario": "简单链路聚合场景，不需要协议协商。",
        "related_commands": ["interface Eth-Trunk", "trunkport"],
        "common_errors": ["模式不匹配导致聚合组无法建立"],
        "troubleshooting": "两端模式必须一致，用 display eth-trunk 检查聚合组状态。",
    },
    "display eth-trunk": {
        "title": "查看 Eth-Trunk 状态",
        "explanation": "查看链路聚合组的成员端口、带宽、负载分担模式等详细信息。",
        "category": "查看与维护",
        "knowledge": "聚合组中部分成员端口 down 时，聚合带宽会相应降低，需要检查物理链路。",
        "scenario": "聚合组故障排查、带宽检查。",
        "related_commands": ["interface Eth-Trunk", "mode manual load-balance"],
        "common_errors": ["成员端口状态不一致", "带宽低于预期"],
        "troubleshooting": "检查每个成员端口的物理状态和聚合状态，确认都是 Up 且参与负载分担。",
    },
    "trunkport": {
        "title": "将物理端口加入 Eth-Trunk",
        "explanation": "将指定的物理接口加入 Eth-Trunk 聚合组作为成员端口。",
        "category": "接口配置",
        "knowledge": "加入聚合组的物理端口不再单独配置，所有配置在 Eth-Trunk 接口上进行。",
        "scenario": "配置链路聚合时将物理端口加入聚合组。",
        "related_commands": ["interface Eth-Trunk", "mode manual load-balance"],
        "common_errors": ["物理端口已有配置导致冲突"],
        "troubleshooting": "先将物理端口配置清空（reset interface），再加入聚合组。",
    },
    "interface Bridge-Aggregation": {
        "title": "创建 Bridge-Aggregation 聚合组（LACP 模式）",
        "explanation": "创建支持 LACP 协议的以太网聚合组，实现动态链路聚合。",
        "category": "接口配置",
        "knowledge": "Bridge-Aggregation 支持 LACP 协议，可以自动管理成员端口的加入和退出，比手动模式更智能。",
        "scenario": "需要自动故障切换和高可靠性的聚合场景。",
        "related_commands": ["interface Eth-Trunk", "mode active", "display eth-trunk"],
        "common_errors": ["LACP 模式配置错误", "活动端口数超限"],
        "troubleshooting": "用 display eth-trunk 检查 LACP 状态，确认活动端口数符合预期。",
    },
    "mode active": {
        "title": "配置 LACP 主动模式",
        "explanation": "将 Bridge-Aggregation 接口设置为 LACP 主动模式，主动发起聚合协商。",
        "category": "接口配置",
        "knowledge": "LACP 有 active（主动）和 passive（被动）两种模式，至少一端为 active 才能建立聚合。",
        "scenario": "配置支持 LACP 的动态链路聚合。",
        "related_commands": ["interface Bridge-Aggregation", "trunkport"],
        "common_errors": ["两端都是 passive 无法建立聚合"],
        "troubleshooting": "确保至少一端配置为 active 模式。",
    },
    "display ethernet-session": {
        "title": "查看以太网聚合会话",
        "explanation": "查看 Eth-Trunk 的 LACP 会话信息，包括活动端口和备份端口。",
        "category": "查看与维护",
        "knowledge": "LACP 会话可以显示哪些端口是活动状态、哪些是备份状态。",
        "scenario": "LACP 聚合组故障排查。",
        "related_commands": ["display eth-trunk", "mode active"],
        "common_errors": [],
        "troubleshooting": "检查活动端口数是否符合设计，备份端口状态是否正常。",
    },
    "acl number": {
        "title": "创建编号 ACL",
        "explanation": "创建指定编号的访问控制列表，用于匹配源 IP 地址等基本流量特征。",
        "category": "安全配置",
        "knowledge": "基本 ACL（2000-2999）只能匹配源 IP，高级 ACL（3000-3999）可以匹配源/目的 IP、端口、协议等。",
        "scenario": "基于源 IP 控制访问权限。",
        "related_commands": ["acl rule", "traffic-filter", "display acl"],
        "common_errors": ["编号冲突", "规则顺序错误"],
        "troubleshooting": "确认编号未使用，用 display acl 检查现有规则。",
    },
    "display acl": {
        "title": "查看 ACL 规则",
        "explanation": "查看已配置的 ACL 规则及其命中计数。",
        "category": "查看与维护",
        "knowledge": "命中计数（Matched）可以判断规则是否被流量匹配到，是验证 ACL 效果的重要依据。",
        "scenario": "检查 ACL 是否生效、规则是否匹配。",
        "related_commands": ["acl", "acl rule", "traffic-filter"],
        "common_errors": ["规则命中计数为 0 表示未匹配到流量"],
        "troubleshooting": "确认 ACL 已应用到接口，检查规则条件是否符合实际流量特征。",
    },
    "reset counters interface": {
        "title": "清空接口统计信息",
        "explanation": "清空指定接口的流量统计计数，便于重新观测流量变化。",
        "category": "查看与维护",
        "knowledge": "接口计数持续累加，清零后方便观察特定时间段内的流量和错码。",
        "scenario": "故障排查前清零计数，再复现故障观察新增计数。",
        "related_commands": ["display interface", "display interface brief"],
        "common_errors": [],
        "troubleshooting": "清零后复现故障，再用 display interface 查看新增计数。",
    },
    "interface NULL0": {
        "title": "创建 NULL0 接口",
        "explanation": "NULL0 是一个特殊的逻辑接口，发送到该接口的流量会被直接丢弃。",
        "category": "三层配置",
        "knowledge": "NULL0 接口常用于路由汇总时丢弃不精确匹配的流量，或防止路由黑 hole。",
        "scenario": "配置路由汇总防止次优路径，或丢弃特定流量。",
        "related_commands": ["ip route-static", "display ip routing-table"],
        "common_errors": ["误配导致正常流量被丢弃"],
        "troubleshooting": "确认路由指向 NULL0 的意图，只在需要丢弃特定流量时使用。",
    },
    "ip route-static <dest> <mask> <next-hop>": {
        "title": "配置静态路由（带下一跳）",
        "explanation": "配置一条指向特定目的网段的静态路由，指定下一跳 IP 地址。",
        "category": "三层配置",
        "knowledge": "静态路由优先级高（默认 60），适合简单网络或作为默认路由。",
        "scenario": "小型网络或出口配置默认路由。",
        "related_commands": ["display ip routing-table", "ip route-static", "ping"],
        "common_errors": ["下一跳不可达", "缺少返回路由"],
        "troubleshooting": "先 ping 下一跳确认可达，再检查对端是否有返回路由。",
    },
    "ip route-static <dest> <mask> <interface>": {
        "title": "配置静态路由（带出接口）",
        "explanation": "配置静态路由时指定出接口而非下一跳 IP，常用于点对点链路。",
        "category": "三层配置",
        "knowledge": "出接口方式不需要解析下一跳 MAC 地址，适合串口或隧道等点对点接口。",
        "scenario": "串行链路或 VPN 隧道场景。",
        "related_commands": ["display ip routing-table", "ip route-static"],
        "common_errors": ["广播型接口使用出接口方式需要配合 ARP"],
        "troubleshooting": "以太网接口建议使用下一跳方式，点对点接口可以使用出接口方式。",
    },
    "ip route-static <dest> <mask> prefernce": {
        "title": "配置静态路由（带优先级）",
        "explanation": "配置静态路由时指定优先级（Preference），数值越小优先级越高。",
        "category": "三层配置",
        "knowledge": "多条到达同一目的网段的路由中，优先级高的优先使用；可用于配置备份路由。",
        "scenario": "配置主备路由，主路由失效时自动切换到备份路由。",
        "related_commands": ["display ip routing-table", "ip route-static"],
        "common_errors": ["优先级数值理解错误（越小越高）"],
        "troubleshooting": "主路由优先级设为 60（默认），备份路由设为 70 或更高。",
    },
    "display ip routing-table destination": {
        "title": "查看特定目的网段的路由",
        "explanation": "在路由表中查找指定目的网段的路由条目。",
        "category": "查看与维护",
        "knowledge": "比查看全部路由表更高效，适合排查特定网段的路由问题。",
        "scenario": "确认特定网段是否有路由、路由下一跳是否正确。",
        "related_commands": ["display ip routing-table", "ip route-static"],
        "common_errors": [],
        "troubleshooting": "确认路由条目存在且 NextHop 可达。",
    },
    "display ip routing-table protocol": {
        "title": "按协议查看路由",
        "explanation": "按路由协议类型（直连、静态、OSPF 等）筛选显示路由表。",
        "category": "查看与维护",
        "knowledge": "可以只看直连路由（direct）、静态路由（static）或动态路由（ospf），快速定位路由来源。",
        "scenario": "确认某类路由是否存在。",
        "related_commands": ["display ip routing-table", "ospf"],
        "common_errors": [],
        "troubleshooting": "用 protocol 参数缩小范围，快速找到需要的路由条目。",
    },
    "display ip routing-table supplementary": {
        "title": "查看路由表补充信息",
        "explanation": "查看路由表的补充信息，如路由优先级、成本等。",
        "category": "查看与维护",
        "knowledge": "多路径路由时会显示所有等价路径，辅助判断负载分担情况。",
        "scenario": "排查多路径路由选路问题。",
        "related_commands": ["display ip routing-table"],
        "common_errors": [],
        "troubleshooting": "确认所有等价路径都符合预期。",
    },
    "display ip interface": {
        "title": "查看接口 IP 详细信息",
        "explanation": "查看指定接口的 IP 配置详情，包括 IP 地址、掩码、MTU 等。",
        "category": "查看与维护",
        "knowledge": "比 brief 更详细，可以看到接口是否禁用了包交换等高级信息。",
        "scenario": "接口 IP 配置排查。",
        "related_commands": ["display ip interface brief", "ip address"],
        "common_errors": [],
        "troubleshooting": "确认 IP 地址和掩码正确，接口状态为 up。",
    },
    "display tcp temporary": {
        "title": "查看 TCP 临时端口",
        "explanation": "查看设备当前建立的 TCP 连接临时端口信息。",
        "category": "查看与维护",
        "knowledge": "可以用来检查设备与外部的 TCP 连接状态，如 SSH 会话、HTTP 请求等。",
        "scenario": "排查连接性问题。",
        "related_commands": ["display network session"],
        "common_errors": [],
        "troubleshooting": "确认 expected 连接是否存在。",
    },
    "display network session": {
        "title": "查看网络会话表",
        "explanation": "查看设备当前所有的网络会话（连接）信息。",
        "category": "查看与维护",
        "knowledge": "会话表记录了当前所有活跃连接，可以用来确认 NAT、防火墙策略是否生效。",
        "scenario": "排查 NAT 或安全策略导致连接不通的问题。",
        "related_commands": ["display tcp temporary", "nat"],
        "common_errors": [],
        "troubleshooting": "确认预期连接在会话表中存在，否则检查安全策略。",
    },
    "display nat session": {
        "title": "查看 NAT 会话表",
        "explanation": "查看设备 NAT 转换的会话信息，包括内部地址和外部地址的映射。",
        "category": "查看与维护",
        "knowledge": "NAT 会话是内网访问外网的必经之路，NAT 表项异常会导致内网无法上网。",
        "scenario": "排查内网无法上网、NAT 转换失败问题。",
        "related_commands": ["display network session", "nat address-group"],
        "common_errors": ["NAT 地址池耗尽", "ACL 未匹配到需要 NAT 的流量"],
        "troubleshooting": "检查 NAT 地址池是否还有可用地址，确认 ACL 正确匹配了需要转换的流量。",
    },
    "nat address-group": {
        "title": "配置 NAT 地址池",
        "explanation": "创建一个 NAT 地址池，用于内网地址转换时提供对外 IP。",
        "category": "NAT",
        "knowledge": "地址池中的 IP 会被分配给内网主机用于访问外网，是 NAT 功能的核心配置。",
        "scenario": "内网主机通过 NAT 访问互联网。",
        "related_commands": ["nat outbound", "acl", "display nat session"],
        "common_errors": ["地址池 IP 与外网接口 IP 不在同一网段", "地址池耗尽"],
        "troubleshooting": "确认地址池网段与外网接口网段匹配，检查是否有足够地址。",
    },
    "nat outbound": {
        "title": "配置 NAT 出方向转换",
        "explanation": "将指定 ACL 匹配的内网流量通过 NAT 地址池转换为外网可路由的地址。",
        "category": "NAT",
        "knowledge": "NAT Outbound 又称 Easy-IP 的反向形式，需要配合地址池使用，适合有公网 IP 池的场景。",
        "scenario": "内网多主机通过公网 IP 池访问外网。",
        "related_commands": ["nat address-group", "acl", "display nat session"],
        "common_errors": ["ACL 未正确匹配内网流量", "地址池未关联"],
        "troubleshooting": "用 display nat session 确认转换是否发生，检查 ACL 和地址池配置。",
    },
    "display nat inbound": {
        "title": "查看 NAT 入方向转换",
        "explanation": "查看端口映射（NAT Inbound）的配置和会话信息。",
        "category": "查看与维护",
        "knowledge": "NAT Inbound 将外网地址映射到内网服务器，实现内网服务器对外提供服务。",
        "scenario": "检查公网服务器端口映射是否正常。",
        "related_commands": ["nat inbound", "display nat session"],
        "common_errors": [],
        "troubleshooting": "确认映射关系正确，外网可以访问到内网服务器。",
    },
    "nat inbound": {
        "title": "配置 NAT 入方向（端口映射）",
        "explanation": "配置端口映射，将公网地址的指定端口转发到内网服务器的对应端口。",
        "category": "NAT",
        "knowledge": "端口映射让内网服务器可以通过公网 IP 对外提供服务，如 Web、邮件服务器。",
        "scenario": "在公网上发布内网 Web 或邮件服务。",
        "related_commands": ["nat address-group", "display nat inbound"],
        "common_errors": ["端口冲突", "内网服务器不可达"],
        "troubleshooting": "确认内网服务器可以访问，端口未被其他服务占用。",
    },
    "display nat outbound": {
        "title": "查看 NAT 出方向转换",
        "explanation": "查看 NAT Outbound 的会话和转换统计信息。",
        "category": "查看与维护",
        "knowledge": "可以确认内网流量是否成功进行了 NAT 转换。",
        "scenario": "排查内网上网问题。",
        "related_commands": ["nat outbound", "display nat session"],
        "common_errors": [],
        "troubleshooting": "确认会话表中有对应的转换记录。",
    },
    "reset acl counter": {
        "title": "清空 ACL 命中计数",
        "explanation": "清空指定 ACL 或所有 ACL 的命中计数，便于重新观测流量匹配情况。",
        "category": "查看与维护",
        "knowledge": "ACL 命中计数累加不清零，清零后可以准确观察特定时间段内的匹配情况。",
        "scenario": "验证 ACL 规则是否生效。",
        "related_commands": ["display acl", "acl rule"],
        "common_errors": [],
        "troubleshooting": "清零后产生预期流量，再查看命中计数是否增加。",
    },
    "display device angle": {
        "title": "查看设备角度（传感器）信息",
        "explanation": "查看设备的温度、电压、风扇转速等传感器信息。",
        "category": "查看与维护",
        "knowledge": "设备硬件异常（过热、电压不稳）可能导致网络不稳定，定期巡检很重要。",
        "scenario": "设备告警时检查硬件状态。",
        "related_commands": ["display device", "display version"],
        "common_errors": [],
        "troubleshooting": "检查温度是否在正常范围内，风扇是否正常转动。",
    },
    "display history-command": {
        "title": "查看历史命令",
        "explanation": "查看当前会话中执行过的命令历史，方便回顾和复用。",
        "category": "基础操作",
        "knowledge": "命令行界面支持上下键翻页查看历史命令，display history-command 可以列表显示。",
        "scenario": "找回之前执行过的命令。",
        "related_commands": ["terminal monitor", "screen-length"],
        "common_errors": ["命令历史默认不保存，重启后清空"],
        "troubleshooting": "用 terminal history 命令保存历史到配置文件。",
    },
    "screen-length": {
        "title": "设置屏幕显示长度",
        "explanation": "设置命令行输出的分页方式，避免长输出被截断或刷屏。",
        "category": "基础操作",
        "knowledge": "默认 screen-length 0 temporary 会关闭分页，所有输出一次性显示，可能刷屏。",
        "scenario": "输出内容很长时控制分页显示。",
        "related_commands": ["display", "terminal monitor"],
        "common_errors": ["关闭分页后输出刷屏难以阅读"],
        "troubleshooting": "执行 screen-length 0 temporary 关闭分页，或默认方式逐屏显示。",
    },
    "terminal monitor": {
        "title": "开启终端日志监控",
        "explanation": "在命令行界面开启日志信息的实时显示，使系统日志直接在终端输出。",
        "category": "系统管理",
        "knowledge": "默认情况下日志只保存到缓冲区，开启后可以在当前会话实时看到日志。",
        "scenario": "调试时实时观察设备日志。",
        "related_commands": ["info-center enable", "display logbuffer"],
        "common_errors": ["忘记关闭导致终端输出过多日志干扰操作"],
        "troubleshooting": "调试完成后执行 undo terminal monitor 关闭。",
    },
    "terminal trap": {
        "title": "开启终端告警监控",
        "explanation": "在命令行界面开启 Trap 告警信息的实时显示。",
        "category": "系统管理",
        "knowledge": "与 terminal monitor 配合使用，可以实时看到设备告警。",
        "scenario": "实时监控设备告警信息。",
        "related_commands": ["terminal monitor", "display trapbuffer"],
        "common_errors": [],
        "troubleshooting": "确认 trap 级别设置正确，告警能正常上报。",
    },
    "reset interface": {
        "title": "重置接口",
        "explanation": "关闭并重新开启指定接口，常用于接口状态异常时恢复。",
        "category": "接口配置",
        "knowledge": "重置接口会使该接口短暂中断，生产环境需谨慎操作。",
        "scenario": "接口状态异常（如一直处于 half-duplex）、需要重新协商时。",
        "related_commands": ["undo shutdown", "display interface"],
        "common_errors": ["误操作导致业务中断"],
        "troubleshooting": "确认影响范围，先在测试环境验证，再在生产环境操作。",
    },
    "resetIpInterface": {
        "title": "重置接口 IP 配置（误写命令）",
        "explanation": "这不是标准 H3C 命令，正确的重置接口 IP 命令应使用 undo ip address。",
        "category": "其他",
        "knowledge": "H3C 命令以 undo 开头撤销配置，没有 resetIpInterface 这种写法。",
        "scenario": "常见输入错误，正确做法是用 undo ip address <ip> <mask>。",
        "related_commands": ["undo ip address", "ip address"],
        "common_errors": ["输入错误命令导致操作失败"],
        "troubleshooting": "使用正确的 undo ip address 命令撤销 IP 配置。",
    },
    "resetNetworkConfiguration": {
        "title": "重置网络配置（误写命令）",
        "explanation": "这不是标准 H3C 命令，正确做法是使用 reset config 恢复出厂或手动清除配置。",
        "category": "其他",
        "knowledge": "H3C 没有 camelCase 风格的命令，所有命令都是小写加连字符的形式。",
        "scenario": "常见输入错误。",
        "related_commands": ["reset config", "save"],
        "common_errors": ["输入错误命令导致操作失败"],
        "troubleshooting": "使用 reset config 恢复出厂配置（需谨慎），或手动清除不需要的配置。",
    },
    "resetSavedConfiguration": {
        "title": "重置已保存配置（误写命令）",
        "explanation": "这不是标准 H3C 命令，H3C 没有此写法。",
        "category": "其他",
        "knowledge": "H3C 命令遵循 Kebab-case 命名规范，没有驼峰命名的命令。",
        "scenario": "常见输入错误。",
        "related_commands": ["reset config"],
        "common_errors": [],
        "troubleshooting": "使用 reset config 清除配置。",
    },
    "displayIpRouteProtocolOspf": {
        "title": "查看 OSPF 路由协议（误写命令）",
        "explanation": "这不是标准 H3C 命令，正确命令是 display ospf brief 或 display ospf peer。",
        "category": "其他",
        "knowledge": "H3C 所有命令均为小写，且用连字符分隔，不支持驼峰命名。",
        "scenario": "常见输入错误。",
        "related_commands": ["display ospf brief", "display ospf peer"],
        "common_errors": [],
        "troubleshooting": "使用 display ospf brief 查看 OSPF 状态。",
    },
    "undoInterfaceBridge-Aggregation": {
        "title": "撤销聚合组接口（误写命令）",
        "explanation": "这不是标准 H3C 命令，正确做法是 undo interface Eth-Trunk <编号> 或删除成员端口。",
        "category": "其他",
        "knowledge": "H3C 中删除聚合组需要先移除所有成员端口，再 undo interface。",
        "scenario": "常见输入错误。",
        "related_commands": ["interface Eth-Trunk", "trunkport"],
        "common_errors": [],
        "troubleshooting": "先将成员端口从聚合组移除，再执行 undo interface Eth-Trunk <编号>。",
    },
    "displayInterface": {
        "title": "查看接口信息（误写命令）",
        "explanation": "这不是标准 H3C 命令，正确命令是 display interface 或 display interface brief。",
        "category": "其他",
        "knowledge": "H3C 命令全部小写，display 后跟接口类型和参数。",
        "scenario": "常见输入错误。",
        "related_commands": ["display interface", "display interface brief"],
        "common_errors": [],
        "troubleshooting": "使用 display interface 查看详细信息，或 display interface brief 查看简要状态。",
    },
    "arpFirewall": {
        "title": "ARP 防火墙（误写命令）",
        "explanation": "这不是标准 H3C 命令，H3C 中没有名为 arpFirewall 的命令，相关功能通过 ACL 和 ARP 白名单实现。",
        "category": "其他",
        "knowledge": "H3C 的 ARP 防护通过 arp whitelist、DAI（动态 ARP 检测）等功能实现。",
        "scenario": "常见输入错误。",
        "related_commands": ["arp whitelist", "acl"],
        "common_errors": [],
        "troubleshooting": "使用 arp whitelist 配置 ARP 白名单，或使用 ACL 配合 traffic-filter 实现 ARP 防护。",
    },
}
